"""Bounded video jobs with durable status, cancellation and on-demand export."""

import json
import logging
import math
import os
import shutil
import subprocess
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor, TimeoutError
from dataclasses import dataclass, field
from pathlib import Path

import cv2

from .counting import RollingCountVoter
from .media import atomic_json, draw_detections, ffmpeg_path, probe_video, subprocess_flags
from .scheduler import BusyError, SupersededError
from .schema import Options
from .tracking import StableTracker
from .detection_gate import DetectionGate, DetectionPausedError

log = logging.getLogger(__name__)
ACTIVE = {"queued", "detecting", "export_queued", "exporting", "canceling"}


@dataclass
class Job:
    data: dict
    cancel: threading.Event = field(default_factory=threading.Event)
    process: object = None
    future: object = None


class VideoJobs:
    def __init__(self, settings, dispatcher, detection_gate=None):
        self.settings, self.dispatcher = settings, dispatcher
        self.detection_gate = detection_gate or DetectionGate()
        self.media_dir = settings.data_dir / "media"
        self.jobs_dir = settings.data_dir / "jobs"
        self.media_dir.mkdir(parents=True, exist_ok=True)
        self.jobs_dir.mkdir(parents=True, exist_ok=True)
        self.lock = threading.RLock()
        self.upload_lock = threading.Lock()
        self.jobs = {}
        self.videos = {}
        self.pool = ThreadPoolExecutor(max_workers=1, thread_name_prefix="video")
        self.closed = False
        self._recover()

    def _recover(self):
        for path in self.media_dir.glob("*.json"):
            try:
                record = json.loads(path.read_text(encoding="utf-8"))
                if record["id"] == path.stem and self.media_path(record).is_file():
                    self.videos[record["id"]] = record
            except (ValueError, KeyError, OSError):
                log.warning("Ignoring invalid media metadata %s", path.name)
        for path in self.jobs_dir.glob("*/status.json"):
            try:
                record = json.loads(path.read_text(encoding="utf-8"))
                if record["id"] != path.parent.name or len(path.parent.name) != 32:
                    continue
                if record["state"] in ACTIVE:
                    record.update(state="failed", error="Server restarted before this operation finished.")
                    atomic_json(path, record)
                self.jobs[record["id"]] = Job(record)
                for partial in path.parent.glob("*.partial*"):
                    partial.unlink(missing_ok=True)
            except (ValueError, KeyError, OSError):
                log.warning("Ignoring invalid job metadata %s", path)
        for partial in self.media_dir.glob("*.partial"):
            partial.unlink(missing_ok=True)

    def media_path(self, record):
        # Filename is generated by this application, never taken from the upload name.
        filename = record["file"]
        if Path(filename).name != filename or "/" in filename or "\\" in filename:
            raise ValueError("Invalid media path")
        return self.media_dir / filename

    def directory(self, id):
        if len(id) != 32 or any(c not in "0123456789abcdef" for c in id):
            raise KeyError("Unknown job")
        return self.jobs_dir / id

    def usage(self):
        total = 0
        for path in self.settings.data_dir.rglob("*"):
            try:
                if path.is_file():
                    total += path.stat().st_size
            except FileNotFoundError:
                pass  # Retention may remove an expired file during this scan.
        return total

    def require_space(self, extra=0):
        if self.usage() + extra > self.settings.disk_budget:
            raise ValueError("Storage limit reached. Delete an old video or job.")
        if shutil.disk_usage(self.settings.data_dir).free < extra + 128 * 1024**2:
            raise ValueError("Insufficient free disk space.")

    def register_upload(self, id, suffix, name, info):
        record = {"id": id, "file": id + suffix, "name": name[:160], "created": time.time(), **info}
        with self.lock:
            atomic_json(self.media_dir / f"{id}.json", record)
            self.videos[id] = record
        return record

    def video(self, id):
        with self.lock:
            if id not in self.videos:
                raise KeyError("Video not found. Upload it again.")
            return dict(self.videos[id])

    def snapshot(self, id):
        with self.lock:
            if id not in self.jobs:
                raise KeyError("Job not found.")
            return dict(self.jobs[id].data)

    def _update(self, job, **values):
        with self.lock:
            job.data.update(values, updated=time.time())
            atomic_json(self.directory(job.data["id"]) / "status.json", job.data)

    def start(self, video_id, options, stride):
        with self.lock:
            if self.closed:
                raise BusyError("Server is shutting down.")
            video = self.video(video_id)
            if sum(j.data["state"] in ACTIVE for j in self.jobs.values()) >= self.settings.max_jobs:
                raise BusyError("Video queue is full. Wait or cancel an existing job.")
            if any(j.data["video_id"] == video_id and j.data["state"] in ACTIVE for j in self.jobs.values()):
                raise BusyError("This video already has an active job. Cancel it before restarting.")
            self.require_space(16 * 1024**2)
            id = uuid.uuid4().hex
            self.directory(id).mkdir()
            job = Job({"id": id, "video_id": video_id, "state": "queued", "progress": 0,
                       "error": None, "export_error": None, "export_ready": False,
                       "created": time.time(), "options": options.model_dump(), "stride": stride,
                       "video": video})
            self.jobs[id] = job
            self._update(job)
            job.future = self.pool.submit(self._detect, job)
            return dict(job.data)

    def cancel(self, id):
        with self.lock:
            job = self.jobs[id]
            if job.data["state"] not in ACTIVE:
                return dict(job.data)
            job.cancel.set()
            self.dispatcher.cancel("job:" + id)
            if job.future and job.future.cancel():
                if job.data["state"] == "export_queued":
                    self._update(job, state="ready", progress=1, export_error="Export canceled; detections are retained.")
                else:
                    self._update(job, state="canceled", error=None)
                return dict(job.data)
            if job.process and job.process.poll() is None:
                try:
                    job.process.terminate()
                except OSError:
                    pass
            self._update(job, state="canceling")
            return dict(job.data)

    def _check(self, job):
        if job.cancel.is_set() or self.closed:
            raise SupersededError("Job canceled.")

    def _call(self, job, frame, options):
        while True:
            self._check(job)
            try:
                generation = self.detection_gate.check()
            except DetectionPausedError:
                job.cancel.wait(.2)
                continue
            def detect(backend, canceled, queued):
                self._check(job)
                self.detection_gate.check(generation)
                result = backend.detect(frame, options)
                self.detection_gate.check(generation)
                return result
            work = self.dispatcher.submit('job:' + job.data['id'], detect, interactive=False)
            started = time.monotonic()
            while True:
                self._check(job)
                try:
                    return work.future.result(timeout=.1)
                except DetectionPausedError:
                    break  # Resume this recorded frame at the next commanded stop.
                except TimeoutError:
                    if time.monotonic() - started > self.settings.inference_timeout:
                        self.dispatcher.cancel('job:' + job.data['id'])
                        raise ValueError('Video inference timed out.')

    @staticmethod
    def timestamp(cap, index, fps, previous):
        measured = cap.get(cv2.CAP_PROP_POS_MSEC) / 1000
        if not math.isfinite(measured) or measured < 0 or (index and measured <= previous):
            measured = index / fps
        return max(measured, previous)

    def _detect(self, job):
        cap = None
        completion = None
        id = job.data["id"]
        partial = self.directory(id) / "timeline.partial.jsonl"
        try:
            self._check(job)
            self._update(job, state="detecting", error=None)
            video = self.video(job.data["video_id"])
            cap = cv2.VideoCapture(str(self.media_path(video)))
            if not cap.isOpened():
                raise ValueError("Cannot open the uploaded video.")
            options = Options(**job.data["options"])
            tracker = StableTracker(options)
            count_voter = RollingCountVoter(options.categories())
            index, previous, output_bytes = 0, 0.0, 0
            sample_count, model_seconds = 0, 0.0
            last_update = 0
            with partial.open("w", encoding="utf-8") as stream:
                while True:
                    self._check(job)
                    ok, frame = cap.read()
                    if not ok:
                        break
                    stamp = self.timestamp(cap, index, video["fps"], previous)
                    previous = stamp
                    if index > self.settings.max_duration * 120 or stamp > self.settings.max_duration + 1:
                        raise ValueError("Decoded video exceeds the duration limit.")
                    if index % job.data["stride"] == 0:
                        started = time.perf_counter()
                        dets = self._call(job, frame, tracker.detection_options)
                        model_seconds += time.perf_counter() - started
                        self._check(job)
                        tracked = tracker.update(dets, stamp, frame)
                        observed = [d.json() for d in tracked]
                        record = {"frame": index, "time": round(stamp, 5), "detections": observed,
                                  "count_summary": count_voter.observe(observed, stamp * 1000)}
                        line = json.dumps(record, ensure_ascii=False, allow_nan=False) + "\n"
                        output_bytes += len(line.encode("utf-8"))
                        if output_bytes > 64 * 1024**2:
                            raise ValueError("Detection timeline exceeds 64 MB. Use a shorter clip or a larger stride.")
                        stream.write(line)
                        sample_count += 1
                    index += 1
                    if time.monotonic() - last_update > 0.5:
                        self.require_space()
                        self._update(job, progress=min(0.99, index / video["frames"]), frames_done=index)
                        last_update = time.monotonic()
            if not index or not sample_count:
                raise ValueError("No frames were decoded.")
            if index < video["frames"] * 0.95:
                raise ValueError("Video decoding stopped early; the file may be truncated.")
            self._check(job)
            with self.lock:
                self._check(job)
                os.replace(partial, self.directory(id) / "timeline.jsonl")
                completion = dict(state="ready", progress=1, frames_done=index, samples=sample_count,
                                  processing_seconds=round(model_seconds, 2))
        except SupersededError:
            completion = dict(state="canceled", error=None)
        except Exception as exc:
            log.exception("Video detection failed")
            completion = dict(state="failed", error=str(exc))
        finally:
            if cap is not None:
                cap.release()
            partial.unlink(missing_ok=True)
            # Terminal states permit deletion. Publish them only after closing
            # decoder and timeline handles (Windows prevents deleting open media).
            with self.lock:
                if job.cancel.is_set():
                    completion = dict(state="canceled", error=None)
                if completion is not None:
                    self._update(job, **completion)

    def timeline(self, id):
        self.snapshot(id)
        path = self.directory(id) / "timeline.jsonl"
        if not path.is_file():
            raise KeyError("Detection results are not ready.")
        return path

    def export(self, id, height=720):
        with self.lock:
            job = self.jobs[id]
            if job.data["state"] != "ready":
                raise BusyError("Finish or cancel the current operation before exporting.")
            if sum(j.data["state"] in ACTIVE for j in self.jobs.values()) >= self.settings.max_jobs:
                raise BusyError("Video queue is full.")
            self.timeline(id)
            self.require_space(64 * 1024**2)
            job.cancel.clear()
            self._update(job, state="export_queued", progress=0, export_error=None, export_height=height)
            job.future = self.pool.submit(self._export, job, height)
            return dict(job.data)

    def _encode(self, job, height, codec):
        video = self.video(job.data["video_id"])
        source = self.media_path(video)
        directory = self.directory(job.data["id"])
        output = directory / "export.partial.mp4"
        scale = min(1, height / video["height"])
        width, out_height = max(2, int(video["width"] * scale) // 2 * 2), max(2, int(video["height"] * scale) // 2 * 2)
        args = [ffmpeg_path(self.settings), "-hide_banner", "-loglevel", "error", "-y",
                "-f", "rawvideo", "-pixel_format", "bgr24", "-video_size", f"{width}x{out_height}",
                "-framerate", str(video["fps"]), "-i", "pipe:0", "-i", str(source),
                "-map", "0:v:0", "-map", "1:a:0?", "-c:v", codec,
                "-preset", "p4" if codec == "h264_nvenc" else "veryfast",
                "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart",
                "-shortest", str(output)]
        cap, process = None, None
        error = None
        logpath = directory / "encoder.log"
        rows = [json.loads(line) for line in self.timeline(job.data["id"]).read_text(encoding="utf-8").splitlines()]
        try:
            cap = cv2.VideoCapture(str(source))
            if not cap.isOpened():
                raise ValueError("Cannot decode source for export.")
            with logpath.open("wb") as stderr:
                process = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL,
                                           stderr=stderr, **subprocess_flags())
                with self.lock:
                    job.process = process
                index, cursor, previous = 0, 0, 0.0
                while True:
                    self._check(job)
                    ok, frame = cap.read()
                    if not ok:
                        break
                    timestamp = self.timestamp(cap, index, video["fps"], previous)
                    previous = timestamp
                    while cursor + 1 < len(rows) and rows[cursor + 1]["time"] <= timestamp:
                        cursor += 1
                    dets = boxes_at_time(rows, cursor, timestamp)
                    frame = cv2.resize(frame, (width, out_height))
                    draw_detections(frame, dets)
                    process.stdin.write(frame.tobytes())
                    index += 1
                    if index % 30 == 0:
                        self.require_space()
                        self._update(job, progress=min(0.99, index / video["frames"]))
                process.stdin.close()
                if index < video["frames"] * 0.95:
                    raise ValueError("Source decoding stopped early during export.")
                if process.wait(timeout=60) != 0:
                    raise ValueError("Encoder exited unsuccessfully.")
            self._check(job)
            metadata = probe_video(output, self.settings.max_duration + 5)
            if metadata["frames"] < index * 0.95 or output.stat().st_size < 512:
                raise ValueError("Encoder produced an incomplete video.")
            return output
        except Exception as exc:
            error = exc
            raise
        finally:
            if cap is not None:
                cap.release()
            if process:
                if process.poll() is None:
                    process.kill()
                process.wait(timeout=5)
                if process.stdin and not process.stdin.closed:
                    try:
                        process.stdin.close()
                    except OSError:
                        pass
            with self.lock:
                job.process = None
            if error:
                output.unlink(missing_ok=True)

    def _export(self, job, height):
        try:
            self._check(job)
            self._update(job, state="exporting")
            try:
                output = self._encode(job, height, "h264_nvenc")
            except Exception:
                self._check(job)
                log.info("Hardware encoder unavailable; retrying with libx264")
                output = self._encode(job, height, "libx264")
            with self.lock:
                self._check(job)
                os.replace(output, self.directory(job.data["id"]) / "export.mp4")
                self._update(job, state="ready", progress=1, export_ready=True, export_error=None)
        except SupersededError:
            self._update(job, state="ready", progress=1, export_error="Export canceled; detections are retained.")
        except Exception as exc:
            log.exception("Export failed")
            path = self.directory(job.data["id"]) / "encoder.log"
            details = path.read_text(encoding="utf-8", errors="replace")[-1600:] if path.exists() else ""
            self._update(job, state="ready", progress=1, export_error=f"Export failed: {exc}. {details}")
        finally:
            (self.directory(job.data["id"]) / "export.partial.mp4").unlink(missing_ok=True)

    def delete_job(self, id):
        with self.lock:
            job = self.jobs[id]
            if job.data["state"] in ACTIVE:
                raise BusyError("Cancel the job and wait for it to stop before deleting.")
            target = self.directory(id).resolve()
            if target.parent != self.jobs_dir.resolve():
                raise ValueError("Invalid job directory.")
            shutil.rmtree(target)
            del self.jobs[id]

    def delete_video(self, id):
        with self.lock:
            if any(j.data["video_id"] == id for j in self.jobs.values()):
                raise BusyError("Delete this video's jobs first.")
            video = self.video(id)
            self.media_path(video).unlink(missing_ok=True)
            (self.media_dir / f"{id}.json").unlink(missing_ok=True)
            del self.videos[id]

    def cleanup(self):
        cutoff = time.time() - self.settings.retention_hours * 3600
        with self.lock:
            for id, job in list(self.jobs.items()):
                if job.data["state"] not in ACTIVE and job.data.get("updated", job.data["created"]) < cutoff:
                    self.delete_job(id)
            for id, video in list(self.videos.items()):
                if video["created"] < cutoff and not any(j.data["video_id"] == id for j in self.jobs.values()):
                    self.delete_video(id)

    def close(self):
        with self.lock:
            self.closed = True
            for id, job in self.jobs.items():
                if job.data["state"] in ACTIVE:
                    self.cancel(id)
        self.pool.shutdown(wait=True, cancel_futures=True)


def boxes_at_time(rows, cursor, timestamp, max_gap=0.25):
    current = rows[cursor]
    if not 0 <= timestamp - current["time"] <= max_gap:
        return []
    visible = [d for d in current['detections'] if not d.get('predicted')
               or d.get('observed_at_ms') is None
               or timestamp * 1000 <= (d.get('prediction_expires_at_ms') or d['observed_at_ms'] + 150)]
    if cursor + 1 == len(rows):
        return visible
    following = rows[cursor + 1]
    gap = following["time"] - current["time"]
    if not 0 < gap <= max_gap:
        return visible
    fraction = (timestamp - current["time"]) / gap
    by_id = {d["track_id"]: d for d in following["detections"] if d.get("track_id") is not None}
    result = []
    for detection in visible:
        target = by_id.get(detection.get("track_id"))
        if target and target["label"] == detection["label"]:
            detection = {**detection, "bbox": [a + fraction * (b - a) for a, b in zip(detection["bbox"], target["bbox"])],
                         "predicted": bool(detection.get('predicted') or target.get('predicted'))}
        result.append(detection)
    return result
